{
    "name": "Harvest Hub",
    "depends": ["base", "mail","fleet","stock"],
    "author": "jatin",
    "category": "Harvest Hub/Agriculture",
    "installable": True,
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "security/ir.rule.xml",
        "data/sequence.xml",
        "wizard/add_diseases_views.xml",
        "views/harvest_crop_order_views.xml",
        "views/harvest_crop_views.xml",
        "views/harvest_process_views.xml",
        "views/harvest_disease_views.xml",
        "views/harvest_farmer_views.xml",
        "views/harvest_location_views.xml",
        "views/harvest_incident_views.xml",
        "views/harvest_menu.xml",
        "views/res_users_views.xml",
        "reports/harvest_crop_templates.xml",
        "reports/harvest_crop_reports.xml",
        "reports/harvest_crop_disease_templates.xml",
        "reports/harvest_crop_process_templates.xml",
        "reports/harvest_crop_material_templates.xml",
    ],
    "application": True,
}
